import{a as S,S as v,i as n}from"./assets/vendor-BSTwZ_tR.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const x="52843742-4f121a35691e2fc0b8477dddd",E="https://pixabay.com/api/",q=15;async function m(t,o=1){try{return(await S.get(E,{params:{key:x,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:q}})).data}catch(r){throw new Error(r.message||"Failed to fetch images")}}const p=document.querySelector(".gallery"),h=document.querySelector(".loading"),g=document.querySelector(".load-more"),y=new v(".gallery a",{caption:!0,captionDelay:250,captionPosition:"bottom",nav:!0,showCounter:!0,loop:!0});function b(t=[]){const o=t.map(({previewURL:r,tags:i,largeImageURL:e,likes:s,views:c,comments:L,downloads:C})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${e}">
          <img
            class="gallery-image"
            src="${r}"
            alt="${i}"
            loading="lazy"
          />
        </a>
        <ul class="info-container">
          <li class="info-box"><p>Likes</p><p>${s}</p></li>
          <li class="info-box"><p>Views</p><p>${c}</p></li>
          <li class="info-box"><p>Comments</p><p>${L}</p></li>
          <li class="info-box"><p>Downloads</p><p>${C}</p></li>
        </ul>
      </li>`).join("");p.insertAdjacentHTML("beforeend",o),y.refresh()}function P(){p.innerHTML="",y.refresh()}function w(){h.classList.remove("is-hidden")}function l(){h.classList.add("is-hidden")}function F(){g.classList.remove("is-hidden")}function u(){g.classList.add("is-hidden")}const A=document.querySelector(".form"),B=document.querySelector(".load-more");let d="",a=1,f=0;A.addEventListener("submit",async t=>{t.preventDefault(),P();const o=t.target.elements["search-text"].value.trim();if(o===""){n.warning({message:"Please enter a search term before submitting.",position:"topCenter",timeout:3e3,backgroundColor:"#FFA000",messageColor:"white",close:!1});return}d=o,a=1,u();try{w();const r=await m(d,a);if(l(),!r.hits.length){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter",timeout:3e3,backgroundColor:"#EF4040",messageColor:"white",close:!1});return}f=r.totalHits,b(r.hits),a*15<f?F():(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topCenter"}))}catch(r){l(),n.error({message:r.message||"An unexpected error occurred.",position:"topCenter",timeout:3e3,backgroundColor:"#EF4040",messageColor:"white",close:!1})}finally{t.target.elements["search-text"].value=""}});B.addEventListener("click",async()=>{a+=1;try{w();const t=await m(d,a);if(l(),!t.hits.length){u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topCenter"});return}b(t.hits);const o=document.querySelector(".gallery-item");if(o){const{height:i}=o.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}a*15>=f&&(u(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topCenter"}))}catch(t){l(),n.error({message:t.message||"An unexpected error occurred.",position:"topCenter",timeout:3e3,backgroundColor:"#EF4040",messageColor:"white",close:!1})}});
//# sourceMappingURL=index.js.map
